# Generated by Django 2.2.4 on 2020-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gosi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gosiname', models.CharField(max_length=200)),
                ('morning', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('date', models.DateField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
