# Generated by Django 2.2.4 on 2020-01-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gosi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gosi',
            name='date',
            field=models.DateField(),
        ),
    ]
